### ISSUE TITLE
ConfigCollection / Parser to collection classes?

### ISSUE THREAD

**Issue by nozavroni** [nozavroni/collections#34]
Maybe it would be useful to create classes to convert yml, xml, json, html, csv, etc. etc. to an appropriate collection type/object? This way you could use collections for configuration? Something to think about... 

Maybe even add a ConfigCollection class that extends MultiCollection? This would be useful to be able to have multiple config files in multiple formats (json, ini, yml, php array, etc.) and then this class/parser/whatever would accept all of these, and then you could call $arr->get("app.bla.blablablee", "default"); to get a config value. You could even do something like this:

config_DEV.yml
```yml
databases:
    default:
        name: database
        user: luke
        pass: 1234pass
        port: 1234
... more
```

config_PROD.yml
```yml
databases:
    default:
        name: prod_db
        user: myproduser
        pass: prodpwd123
        port: 2306
```

Given these two files, you could do something like:
```php
$config = new ConfigCollection();
$config->import("config_DEV.yml", "DEV");
$config->import("config_PROD.yml", "PROD");
$config->setEnv($_ENV['environment']); // this = DEV
$config->get("databases.default.name", "default"); // returns "database"
$config->get("databases.default.foo", "default"); // returns "default"
$config->setEnv("PROD"); 
$config->get("databases.default.name"); // returns "prod_db"
```

This would allow multi environment configuration
