### ISSUE TITLE
Add collapse method

### ISSUE THREAD

**Issue by nozavroni** [nozavroni/collections#36]
Add a collapse method to MultiCollection that collapses a multi-dimensional array/collection into a one-dimensional one. So this:

```yml
users:
    luke: 
        firstname: luke
        lastname: visinoni
        email: luke.visinoni@gmail.com
    dude: 
        firstname: the
        lastname: dude
        email: thedude@lebowski.com
    jeff: 
        firstname: jeff
        lastname: lebowski
        email: jlebowski@whereisbunny.com
```

Becomes this:

```yml
NOT SURE: Look at how Laravel handles it
```
